"""add fence_triggers table

Revision ID: 0e30fc242b60
Revises: 
Create Date: 2026-05-01 20:43:53.092185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e30fc242b60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fence_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fence_id', sa.Integer(), nullable=False),
    sa.Column('figure_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fence_id'], ['geo_fences.id'], ),
    sa.ForeignKeyConstraint(['figure_id'], ['red_figures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fence_triggers_fence_id'), 'fence_triggers', ['fence_id'], unique=False)
    op.create_index(op.f('ix_fence_triggers_id'), 'fence_triggers', ['id'], unique=False)
    op.create_index(op.f('ix_fence_triggers_user_id'), 'fence_triggers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fence_triggers_user_id'), table_name='fence_triggers')
    op.drop_index(op.f('ix_fence_triggers_id'), table_name='fence_triggers')
    op.drop_index(op.f('ix_fence_triggers_fence_id'), table_name='fence_triggers')
    op.drop_table('fence_triggers')
    # ### end Alembic commands ###
